### ISSUE TITLE
x100cmd export 実行時にCH000（プライオリティCH）が取り込まれない

### ISSUE THREAD

**Issue by k-ishii1020** [bellx2/x100cmd#20]
表題のとおりです。

私も指摘があるまで000CHの存在を忘れていました。import(書き出し）は問題ないようです。
よろしくお願いいたします。

**Comment by bellx2** [comment]
特殊性もあり1番からにした経緯があります。また、純正のエディタでもβ版は編集可能でしたが、リリース版では0chは編集対象外になっています。

特にこだわりは無いので対応予定にしておきます。

**Comment by k-ishii1020** [comment]
ご対応ありがとうございます！動作確認しました
